# [START gae_python37_cloudsql_config]
runtime: python39

env_variables:
  CLOUD_SQL_USERNAME: Bhavith123
  CLOUD_SQL_PASSWORD: Bhavith@123
  CLOUD_SQL_DATABASE_NAME: Bhavith123
  CLOUD_SQL_CONNECTION_NAME: engaged-upgrade-344514:asia-south1:bhavith1
# [END gae_python37_cloudsql_config]
